import argparse
import csv
import json
import os

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import matplotlib.pyplot as plt
from matplotlib import font_manager
from matplotlib import rcParams


NOTO_CJK_FONT_PATH = "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"
if os.path.exists(NOTO_CJK_FONT_PATH):
    font_manager.fontManager.addfont(NOTO_CJK_FONT_PATH)

rcParams["font.family"] = "sans-serif"
rcParams["font.sans-serif"] = ["Noto Sans CJK JP", "DejaVu Sans"]
rcParams["axes.unicode_minus"] = False


DEFAULT_JSON_BASELINE = "./result/legacy_json/OPPU-k0-Base-movie-result"
DEFAULT_JSON_DRIFT_FILES = {
    0: "./result/original/AntiOPPU-k0-Base-movie-result-0drift",
    25: "./result/original/AntiOPPU-k0-Base-movie-result-25drift",
    50: "./result/original/AntiOPPU-k0-Base-movie-result-50drift",
    75: "./result/original/AntiOPPU-k0-Base-movie-result-75drift",
    100: "./result/original/AntiOPPU-k0-Base-movie-result-100drift",
}

DEFAULT_CSV_PATH = "./result/strict_compare/movie_tagging/summary.csv"

METHOD_STYLES = {
    "base": {"color": "#7f7f7f"},
    "ewc": {"color": "#1f77b4"},
    "lwf": {"color": "#ff7f0e"},
    "ewc-lwf": {"color": "#2ca02c"},
}

METRIC_LABELS = {
    "query_accuracy": "Query - Accuracy",
    "query_f1": "Query - F1",
    "accuracy_gap": "Accuracy Gap",
    "f1_gap": "F1 Gap",
}

METRIC_LINE_STYLES = {
    "query_accuracy": {"linestyle": "-", "marker": "o"},
    "query_f1": {"linestyle": "--", "marker": "s"},
    "accuracy_gap": {"linestyle": "-.", "marker": "v"},
    "f1_gap": {"linestyle": ":", "marker": "P"},
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot comparison figures from legacy JSON results or summary CSV data."
    )
    parser.add_argument(
        "--mode",
        choices=["csv", "json"],
        default="csv",
        help="Input mode. `csv` reads summary.csv, `json` keeps the old fixed-file behavior.",
    )
    parser.add_argument(
        "--csv_path",
        default=DEFAULT_CSV_PATH,
        help="Path to summary.csv generated by run_drift_method_experiments.py.",
    )
    parser.add_argument(
        "--metrics",
        nargs="+",
        default=["query_accuracy", "query_f1"],
        help="CSV columns to plot.",
    )
    parser.add_argument(
        "--output_path",
        default=None,
        help="Optional output image path. If omitted, a sensible default is used.",
    )
    parser.add_argument(
        "--title",
        default=None,
        help="Optional figure title.",
    )
    parser.add_argument(
        "--no_show",
        action="store_true",
        help="Save figure without calling plt.show().",
    )
    return parser.parse_args()


def load_legacy_json_results():
    with open(DEFAULT_JSON_BASELINE, "r") as f:
        oppu_result = json.load(f)

    anti_results = {}
    for drift, file_path in DEFAULT_JSON_DRIFT_FILES.items():
        with open(file_path, "r") as f:
            anti_results[drift] = json.load(f)

    return oppu_result, anti_results


def create_legacy_json_plot(output_path=None, title=None, show=True):
    oppu_result, anti_results = load_legacy_json_results()

    drift_levels = sorted(DEFAULT_JSON_DRIFT_FILES.keys())
    oppu_acc = oppu_result["accuracy"]
    oppu_f1 = oppu_result["f1"]

    anti_acc = [anti_results[drift]["accuracy"] for drift in drift_levels]
    anti_f1 = [anti_results[drift]["f1"] for drift in drift_levels]

    fig, ax = plt.subplots(figsize=(10, 6))

    ax.scatter([0], [oppu_acc], marker="s", s=100, label="OPPU Accuracy", color="blue")
    ax.scatter([0], [oppu_f1], marker="^", s=100, label="OPPU F1", color="blue")
    ax.plot(
        drift_levels,
        anti_acc,
        marker="o",
        linewidth=2,
        markersize=8,
        label="AntiOPPU Accuracy",
        color="orange",
    )
    ax.plot(
        drift_levels,
        anti_f1,
        marker="v",
        linewidth=2,
        markersize=8,
        label="AntiOPPU F1",
        color="green",
    )

    for i, drift in enumerate(drift_levels):
        ax.annotate(
            f"{anti_acc[i]:.3f}",
            (drift, anti_acc[i]),
            textcoords="offset points",
            xytext=(0, 10),
            ha="center",
            fontsize=9,
        )
        ax.annotate(
            f"{anti_f1[i]:.3f}",
            (drift, anti_f1[i]),
            textcoords="offset points",
            xytext=(0, 10),
            ha="center",
            fontsize=9,
        )

    ax.annotate(
        f"{oppu_acc:.3f}",
        (0, oppu_acc),
        textcoords="offset points",
        xytext=(0, 10),
        ha="center",
        fontsize=9,
    )
    ax.annotate(
        f"{oppu_f1:.3f}",
        (0, oppu_f1),
        textcoords="offset points",
        xytext=(0, 10),
        ha="center",
        fontsize=9,
    )

    ax.set_xlabel("Drift Level (%)", fontsize=12)
    ax.set_ylabel("Performance", fontsize=12)
    ax.set_title(title or "Performance Comparison: OPPU vs AntiOPPU", fontsize=14)
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    final_output_path = output_path or "./result/legacy_plots/performance_comparison.png"
    os.makedirs(os.path.dirname(os.path.abspath(final_output_path)), exist_ok=True)
    plt.savefig(final_output_path, dpi=300, bbox_inches="tight")
    if show:
        plt.show()
    else:
        plt.close(fig)
    return final_output_path


def convert_value(row, key):
    value = row.get(key)
    if value is None or value == "":
        return None
    return float(value)


def load_csv_results(csv_path):
    with open(csv_path, "r", newline="") as f:
        reader = csv.DictReader(f)
        rows = []
        for row in reader:
            parsed_row = {"drift": int(row["drift"]), "method": row["method"]}
            for key in METRIC_LABELS:
                parsed_row[key] = convert_value(row, key)
            rows.append(parsed_row)
    return rows


def group_rows_by_method(rows):
    grouped = {}
    for row in rows:
        grouped.setdefault(row["method"], []).append(row)
    for method_rows in grouped.values():
        method_rows.sort(key=lambda item: item["drift"])
    return grouped


def resolve_output_path(csv_path, output_path):
    if output_path:
        return output_path
    csv_dir = os.path.dirname(os.path.abspath(csv_path))
    return os.path.join(csv_dir, "summary_plot.png")


def create_single_capability_plot(grouped_rows, rows, metrics, capability_name, output_path, title, show):
    fig, ax = plt.subplots(figsize=(12, 7))

    for method, method_rows in grouped_rows.items():
        drifts = [row["drift"] for row in method_rows]
        style = METHOD_STYLES.get(method, {"color": None})

        for metric in metrics:
            values = [row[metric] for row in method_rows]
            if all(value is None for value in values):
                continue

            line_style = METRIC_LINE_STYLES.get(metric, {"linestyle": "-", "marker": "o"})
            short_metric_name = "Accuracy" if "accuracy" in metric else "F1"
            label = f"{method} - {short_metric_name}"
            ax.plot(
                drifts,
                values,
                linewidth=2,
                markersize=7,
                label=label,
                color=style.get("color"),
                linestyle=line_style["linestyle"],
                marker=line_style["marker"],
            )

            for drift, value in zip(drifts, values):
                if value is None:
                    continue
                ax.annotate(
                    f"{value:.3f}",
                    (drift, value),
                    textcoords="offset points",
                    xytext=(0, 8),
                    ha="center",
                    fontsize=8,
                )

    ax.set_xlabel("Drift Level (%)", fontsize=12)
    ax.set_ylabel("Score", fontsize=12)
    ax.set_title(title or capability_name, fontsize=14)
    ax.set_xticks(sorted({row["drift"] for row in rows}))
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=9, ncol=2)

    plt.tight_layout()
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    if show:
        plt.show()
    else:
        plt.close(fig)


def create_csv_plot(csv_path, metrics, output_path=None, title=None, show=True):
    rows = load_csv_results(csv_path)
    grouped_rows = group_rows_by_method(rows)

    invalid_metrics = [metric for metric in metrics if metric not in METRIC_LABELS]
    if invalid_metrics:
        raise ValueError(f"Unsupported metrics: {invalid_metrics}")

    final_output_path = resolve_output_path(csv_path, output_path)
    create_single_capability_plot(
        grouped_rows=grouped_rows,
        rows=rows,
        metrics=metrics,
        capability_name="Query",
        output_path=final_output_path,
        title="Query" if title is None else title,
        show=show,
    )

    return final_output_path


def main():
    args = parse_args()

    if args.mode == "json":
        output_path = create_legacy_json_plot(
            output_path=args.output_path,
            title=args.title,
            show=not args.no_show,
        )
    else:
        output_path = create_csv_plot(
            csv_path=args.csv_path,
            metrics=args.metrics,
            output_path=args.output_path,
            title=args.title,
            show=not args.no_show,
        )

    if isinstance(output_path, dict):
        for name, path in output_path.items():
            print(f"Saved {name} figure to: {path}")
    else:
        print(f"Saved figure to: {output_path}")


if __name__ == "__main__":
    main()
